version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - ikar-network

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: ikar_db
      MYSQL_USER: ikaruser
      MYSQL_PASSWORD: ikarpass
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - ikar-network

volumes:
  db_data:

networks:
  ikar-network:


